version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps): update dependency"
      prefix-development: "chore(deps-dev): update dependency"
      include: scope
    labels:
      - "Status ✨ New"
      - "Type 🔗 Dependencies"
    pull-request-branch-name:
      separator: "-"
    reviewers:
      - "CheeseTastisch"